version: '3'

services:

  server:
    image: node:21-alpine
    volumes:
      - .:/app
    command: sh -c "cd /app && yarn server"
    ports:
      - 8088:8088
      - 8089:8089
    healthcheck:
      test: rm -fr ping && wget server:8088/ping
      interval: 1s
      timeout: 2s
      retries: 60
    depends_on:
      redis:
        condition: service_healthy

  worker:
    image: alcalyn/hex-distributed-ai-worker:latest
    build: ./src/worker
    volumes:
      - .:/app
    command: sh -c "cd /app && yarn worker"

  redis:
    image: redis:7
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 2s
      retries: 30
